"""

Revision ID: 41fce43283b1
Revises: 1e2a8f2ed892
Create Date: 2024-10-21 21:06:02.059066

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41fce43283b1"
down_revision: Union[str, None] = "1e2a8f2ed892"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pub_receipts",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("creator_oid", sa.Uuid(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False, comment="Уникальный идентификатор"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["creator_oid"],
            ["users.oid"],
            name=op.f("fk_pub_receipts_creator_oid_users"),
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_pub_receipts")),
        sa.UniqueConstraint("oid", name=op.f("uq_pub_receipts_oid")),
    )
    op.create_table(
        "pub_receipt_items",
        sa.Column("position_title", sa.String(length=128), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pub_receipt_oid", sa.Uuid(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False, comment="Уникальный идентификатор"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["pub_receipt_oid"],
            ["pub_receipts.oid"],
            name=op.f("fk_pub_receipt_items_pub_receipt_oid_pub_receipts"),
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_pub_receipt_items")),
        sa.UniqueConstraint("oid", name=op.f("uq_pub_receipt_items_oid")),
    )
    op.create_table(
        "pub_receipt_splits",
        sa.Column("user_oid", sa.Uuid(), nullable=False),
        sa.Column("share", sa.Integer(), nullable=False),
        sa.Column("pub_receipt_item_oid", sa.Uuid(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False, comment="Уникальный идентификатор"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["pub_receipt_item_oid"],
            ["pub_receipt_items.oid"],
            name=op.f("fk_pub_receipt_splits_pub_receipt_item_oid_pub_receipt_items"),
        ),
        sa.ForeignKeyConstraint(
            ["user_oid"],
            ["users.oid"],
            name=op.f("fk_pub_receipt_splits_user_oid_users"),
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_pub_receipt_splits")),
        sa.UniqueConstraint("oid", name=op.f("uq_pub_receipt_splits_oid")),
    )
    op.create_unique_constraint(op.f("uq_friends_oid"), "friends", ["oid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_friends_oid"), "friends", type_="unique")
    op.drop_table("pub_receipt_splits")
    op.drop_table("pub_receipt_items")
    op.drop_table("pub_receipts")
    # ### end Alembic commands ###
